### ISSUE TITLE
DeployPackages - display information about step which is currently undergoing

### ISSUE THREAD

**Issue by Halky** [Rhetos/Rhetos#110]
**Is your feature request related to a problem? Please describe.**
During deployment some steps such as dropping columns or recomputing could take longer time than expected. It would be nice to have information about current executing long running step. At the moment we only get information about longer running steps after they are completed (with information how long did the step took the time to finish).

**Describe the solution you'd like**
It would be handy if we could get information in DeployPackages which step is it executing if such step takes some longer time.
E.g. In progress -  Dropping column Column1 on table Schema1.Table1

**Comment by bantolov** [comment]
Hi,
This issue is solved in Rhetos version 4.1:
"Long operation" warning will be reported on deployment if certain operations take longer than a minute (by default). This includes:

* Loading and saving data. This can help with debugging slow recomputes for KeepSynchronized entities on deployment.
* Data-migrations scripts.
* Database updates (dropping a column, e.g.),
* Some other SQL scripts that are executed with SqlTransactionBatches.

These operations will start a new thread that reports a warning if the operation lasts longer than a minute, without breaking the operation.
