### ISSUE TITLE
Clarification when will AfterSave took place if parent Entity is saved in Action

### ISSUE THREAD

**Issue by Halky** [Rhetos/Rhetos#116]
For simplicity sake, let's imagine we have Action called MasterAction which only executes two Actions - Action1 and Action2.
Action1 inserts new row in Entity1 while Action2 inserts new row in Entity2
Entity1 has AfterSave conecpt which updates row which should be made by Action2.
Entity2 has AfterSave concept which updates row which should be made by Action1.
What will happend? :)

I'm guessing what I'm actually asking is - when does the "save" command actually takes place in regards with AfterSave concepts - is it after we made changes to row / table or after we commit those changes? Does transaction isolation level has any impact on behavior? Is the orden even guaranteed?

**Comment by damirdean** [comment]
AfterSave occures at the end of Save method of the Entity, after changes to the database are made. It occures in the same transaction in which your AfterSave code will run, so you can consume those changes in your code/query. You can find exact place where your AfterSave code will be placed in ServerDom.Repositroies.cs, just find apropriate tag: /*DataStructureInfo WritableOrm AfterSave YourModule.YourEntity*/
However, the code you described will not work because Action1 will be runned first and at that time Entity2 does not exist yet in the database. Your AfterSave on Entity1 tries to update nonexisting Entity2.
