### ISSUE TITLE
Checking RowPermissions for other user

### ISSUE THREAD

**Issue by lija9** [Rhetos/Rhetos#123]
Hi,
how can I check permissions on an entity for another user (not the user that is currently logged in)?

Example:
if (repository.ENTITY.Filter(repository.ENTITY.Query().Where(x => x.ID == SOMEID), new Common.RowPermissionsWriteItems()).Count() == 0)

This code will check if the user that is currently logged in has the write permission for specific record.
I need to check if user with ID "xy" has write permission for that record.

Thanks

**Comment by bantolov** [comment]
There are different solutions to this, depending on the use case, please elaborate what problem do you need to solve. Row permissions in a specific application are usually implemented by directly reading `context.UserInfo` in the rule implementation, so we need to provide a different user for the execution context, by using dependency injection.

**When writing unit tests**, or similar environments, you can manually choose the user for whom the operation is executed. This is done by registering the user instance at the beginning of the processing request, for example see usage of [AddFakeUser](https://github.com/Rhetos/Rhetos/blob/master/CommonConcepts/CommonConceptsTest/CommonConcepts.Test/Helpers/RhetosTestContainerExtensions.cs) method in unit test [KeepSyncRepositoryMembers](https://github.com/Rhetos/Rhetos/blob/master/CommonConcepts/CommonConceptsTest/CommonConcepts.Test/ComputedFromTest.cs). It must be done immediately at the beginning of the `using` block, and the user should not be changed withing the block. After that, any row permissions within this scope block will be executed with that user's rights.

**In application run-time environment**, there is less control for changing the current user. Two plugins are available for user impersonation, that allow power users to temporarily work as another user: [AspNetFormsAuthImpersonation](https://github.com/Rhetos/AspNetFormsAuthImpersonation) and [WindowsAuthImpersonation](https://github.com/Rhetos/WindowsAuthImpersonation).

There is no good solution for changing the current user in the middle of a single request, since the user's permissions may be cached. Alternatively, you might refactor some part of the row permissions rules into a separate method that takes a username as a parameter, then call this method to check another user's permissions.

**Comment by lija9** [comment]
Thank you for the answer.
My scenario was: I, as user X need to share Document with user Y. In my action I need to check if user Y has write permission on that Document. If he does not have permission he must be added as 
Associate to that Document  (that is another action that should be called). 
It was handled in another way so this thread can be closed.
