### ISSUE TITLE
Nullable AutoCode

### ISSUE THREAD

**Issue by marijok** [Rhetos/Rhetos#129]
Hi guys,

I need something like this:

```C
Entity Position {
    AuditAndLoggingAll;

    Reference OrganizationUnitPosition MasterData.OrganizationUnitPosition;
    
    ShortString PositionNumber { 
            AutoCodeForEach Logistics.Position.OrganizationUnitPosition;
            DenyUserEdit; 
            DefaultValue 'item => item.ServiceID != null ? "++++++" : null'; } 
    
    ShortString JobNumber {
            AutoCode; 
            DenyUserEdit; 
            DefaultValue 'item => item.ServiceID == null ? (_domRepository.MasterData.OrganizationUnitPosition.Query().Single(x => x.ID == item.OrganizationUnitPositionID).Period.EndDate.Value.ToString("yy") + "++++++++") : null'; }

    LongString Description;
    Reference Service MasterData.Service;

    Deactivatable;
  }
```

but AutoCode does not insert null. What would be the best way to get around this?

**Comment by bantolov** [comment]
Current implementation of **AutoCode considers `null` same as `+`: it will generate new codes if the null value is provided**. If we simply allow null values in AutoCode, we should also modify the unique constraint to allow multiple null values, and probably implement some logic to generate new codes on update (AutoCode currently handles only inserts). Are you planning to assign new coded for those "skipped" items later?

## Solution 1
You might developer your custom code to set the new `PositionNumber` and `JobNumber` in SaveMethod...Initialization, or encapsulate that code in a new custom concept.

## Solution 2
Alternatively, depending on you requirements, you could change the data model in order to **group properties related to Service**, and simplify the business logic. See the example below.

This way you don't need `DefaultValue` and `AutoCode` to handle `null` values.
Note that the `Service` property is **required** in the extension table, but ServicePosition will not be inserted for Positions without Service.

```C
Entity Position
{
    AuditAndLoggingAll;
    Deactivatable;

    Reference OrganizationUnitPosition MasterData.OrganizationUnitPosition;
    LongString Description;
}

Entity ServicePosition
{
    Extends Position;
    Reference Service MasterData.Service { Required; }
    ShortString PositionNumber {
            AutoCodeForEach Logistics.Position.OrganizationUnitPosition;
            DenyUserEdit;
        }

    ShortString JobNumber {
        AutoCode;
        DenyUserEdit;
        DefaultValue 'item => _domRepository.MasterData.OrganizationUnitPosition
            .Query().Single(x => x.ID == item.OrganizationUnitPositionID)
            .Period.EndDate.Value.ToString("yy") + "++++++++"'; }
}
```

**Comment by marijok** [comment]
Tnx. Am trying solution 2. Extended entity "ServicePosition" can't access "OrganizationUnitPosition" from "Position" entity. How do we access "OrganizationUnitPosition" from "ServicePostion"?

**Comment by bantolov** [comment]
AutoCodeForEach concept cannot use a property from another entity.
I have corrected the example above by moving OrganizationUnitPosition to ServicePosition, but I am not sure that is what you need.

If not, you will have to write you own C# code to handle generating `PositionNumber` codes.
