### ISSUE TITLE
AutocodeForEach on multiple properties

### ISSUE THREAD

**Issue by ikudeljnj** [Rhetos/Rhetos#159]
Hello!

My case is as follows:

Entity Document {}
Entity DocumentItem { DocumentNumber, WareTypeID, CommodityID, DocumentID}

DocumentNumber is AutocodeForEach (DocumentID).

However, what I actually need is AutocodeForEach(DocumentID, WareTypeID) and AutocodeForEach(DocumentID, CommodityID)

So, let's say we have four items in one document, two with different ware types and two with different commodities. I would want my document items to be numbered 1,2 and 1,2

What do you suggest in such case?

**Comment by bantolov** [comment]
There is no out-of-the-box solution for this feature.
Here are different approaches that you could try:

1. Implement the DocumentNumber generator manually in C#, in a classic way, inside the Save method of DocumentItem, based on the exiting records in the database. You can do that in DSL script with concepts [SaveMethod...Initialization](https://github.com/Rhetos/Rhetos/wiki/Low-level-object-model-concepts).
2. Change the data model to by splitting the DocumentItem entity into separate entities, so that each entity can have a simpler AutoCodeForEach feature. This is probably not applicable in the current situation, since it might require adding a detail of the detail entity.
3. You could implement a new concept, similar to AutoCodeForEach, that would work with multiple grouping properties (copy and modify classes [AutoCodeForEachInfo](https://github.com/Rhetos/Rhetos/blob/master/CommonConcepts/Plugins/Rhetos.Dsl.DefaultConcepts/SimpleBusinessLogic/AutoCodeForEachInfo.cs), [AutoCodeForEachCodeGenerator](https://github.com/Rhetos/Rhetos/blob/master/CommonConcepts/Plugins/Rhetos.Dom.DefaultConcepts/SimpleBusinessLogic/AutoCodeForEachCodeGenerator.cs), and [AutoCodeHelper](https://github.com/Rhetos/Rhetos/blob/master/CommonConcepts/Plugins/Rhetos.Dom.DefaultConcepts/SimpleBusinessLogic/AutoCodeHelper.cs)).
