### ISSUE TITLE
UTF8 encoding

### ISSUE THREAD

**Issue by JosipBaketaric** [Rhetos/Rhetos#163]
**Describe the bug**
When loading scripts, AfterDeploy uses Default ENCODING ([not advised by Microsoft](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.default?view=netframework-4.8)) and if the script contains any special characters like 'č', 'ž' etc. it turns them to gibberish.

**To Reproduce**
Just enter some special characters inside the script and compare the result.

**Comment by bantolov** [comment]
We should probably use UTF8Encoding to load all files, including .rhe scripts and data migration scripts.

Current **workaround** for this issue is to save the .rhe and .sql files with encoding "UTF8 with BOM", if file contains non-English characters, to make sure it is always interpreted correctly.

This change could break backward compatibility for some applications. It should be released in next major release, along with instructions for reviewing the existing application's files.

**Comment by bantolov** [comment]
Closed by #203.

Since Rhetos v3.0, .rhe and .sql files are read with UTF-8 encoding by default, with a fallback to default system encoding for backward compatibility:

1. If the file contains [BOM](https://en.wikipedia.org/wiki/Byte_order_mark), the specified encoding will be used to read the file.
2. Otherwise, the UTF-8 encoding will be used to read the file.
3. After reading the file, if it contains an invalid unicode character [REPLACEMENT CHARACTER](https://en.wikipedia.org/wiki/Specials_(Unicode_block)), Rhetos will show the warning and read the file with default system encoding.
