### ISSUE TITLE
Error saving object using ChangesOnChangedItems

### ISSUE THREAD

**Issue by vinkoSego** [Rhetos/Rhetos#179]
I have 2 objects: ReceiptItem which is a Polymorfic DocumentItem and computed state AnnouncedState.
Whenever ReceiptItem is changed, if it satisfies conditions, AnnouncedState will insert/update.

Now, updateing existing receiptItem works good, but on insert I get error.

```c
Entity ReceiptItem
  {
    AuditAndLoggingAll;
    
    Reference Receipt Warehouse.Receipt { Required; } //Zaglavlje primke
    ShortString DocumentItemNumber { DenyUserEdit; } //Redni broj stavke (unutar zaglavlja)
    Reference State MasterData.WarehouseDocumentItemState { Required; } //Status        
    Reference ShipmentItem Logistics.ShipmentItem; //veza prema stavci pošiljke
    
    Reference Commodity MasterData.Commodity; //Artikl
    Reference WareType MasterData.WareType; //Vrsta robe
    Reference Project MasterData.Project; //Projekt        
    Reference OfficeLocation MasterData.Company; //Poslovnica

    Decimal Mass; // in kg
    Decimal Volume; // in meters

    Decimal NoBulkPackages;
    Decimal Amount;

    // nasljeđivanje? zašto ovako?
    Reference DocumentItem Warehouse.DocumentItem;
    Is Warehouse.DocumentItem
    {
        Implements Warehouse.DocumentItem.Document 'ReceiptID';
    }   
    
    // all receipt items add to IncomingAnnounced state
    Is Warehouse.WarehouseStateDocumentItem 'IncomingAnnouncedAmount'
    {
        Implements Warehouse.WarehouseStateDocumentItem.Document 'ReceiptID';
        Implements Warehouse.WarehouseStateDocumentItem.DocumentItem 'ID';

        Implements Warehouse.WarehouseStateDocumentItem.IncomingAnnouncedNoBulkPackages 'NoBulkPackages'; // najava ulaza
        Implements Warehouse.WarehouseStateDocumentItem.OutgoingAnnouncedNoBulkPackages 'null'; // najava izlaza
        Implements Warehouse.WarehouseStateDocumentItem.OutgoingReservationNoBulkPackages 'null'; // rezervacija izlaza
        
        Implements Warehouse.WarehouseStateDocumentItem.IncomingAnnouncedAmount 'Amount'; // najava) ulaza
        Implements Warehouse.WarehouseStateDocumentItem.OutgoingAnnouncedAmount 'null'; // najava izlaza
        Implements Warehouse.WarehouseStateDocumentItem.OutgoingReservationAmount 'null'; // rezervacija izlaza
    }
...
Announced State:

SqlQueryable ComputeWarehouseIncomingAnnouncedState <SQL\ComputeWarehouseIncomingAnnouncedState.sql>        
    {
      Reference Document Warehouse.Document;
      Reference Owner MasterData.Company;
      ShortString DocumentCode;
      Reference DocumentItem Warehouse.DocumentItem;
      ShortString DocumentItemNumber;
      Reference Commodity MasterData.Commodity;        
      Reference WareType MasterData.WareType;
      Reference Project MasterData.Project;
      Reference OfficeLocation MasterData.Company;
      Decimal Mass;
      Decimal Volume;
      Decimal NoBulkPackages;
      Decimal Amount;

      ChangesOnChangedItems Warehouse.ReceiptItem 'IncomingAnnouncedChangeData[]' ' changedItems => changedItems.Select(x => x.ID).Distinct().Select( x => new IncomingAnnouncedChangeData { DocumentItemID = x}).ToArray()';
 FilterBy 'Warehouse.IncomingAnnouncedChangeData[]' 
      '(repository, changedItems) =>
          {
              var documentItemIDs = changedItems.Where(changedItem => changedItem.DocumentItemID.HasValue).Select(changedItem => changedItem.DocumentItemID.Value).ToList();
              return repository.Warehouse.ComputeWarehouseIncomingAnnouncedState.Query().Where(item => documentItemIDs.Contains(item.DocumentItemID.Value)).ToSimple().ToArray();
          }
      ';

    }
Parameter IncomingAnnouncedChangeData
    {
        Reference DocumentItem Warehouse.DocumentItem;
    }

    Entity WarehouseIncomingAnnouncedState
	  {
      AuditAndLoggingAll;

      FilterBy 'Warehouse.IncomingAnnouncedChangeData[]' 
      '(repository, changedItems) =>
          {
              var documentItemIDs = changedItems.Select(changedItem => changedItem.DocumentItemID.Value).ToList();
              return repository.Warehouse.WarehouseIncomingAnnouncedState.Query().Where(item => documentItemIDs.Contains(item.DocumentItemID.Value)).ToSimple().ToArray();
          }
      ';

      ComputedFrom Warehouse.ComputeWarehouseIncomingAnnouncedState
      {
          AllProperties;
          KeepSynchronized;
      }	       
    }
```

Problem is:
When I save ReceiptItem, during the process I set AnnouncedState.DocumentItemID = DocumenItemID, but since everything is in a single transaction, there is not ID in the DocumentItem table in DB. That results in error saying I am referencing non existant reference

**Rhetos.UserException: 'It is not allowed to enter the record. The entered value references nonexistent record.'**

"SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_WarehouseIncomingAnnouncedState_DocumentItem_DocumentItemID". The conflict occurred in database "ZGSped", table "Warehouse.DocumentItem_Materialized", column 'ID'."

**Comment by bantolov** [comment]
Hi,
The problem here is that inserting ReceiptItem has two consequences:

1. Inserting WarehouseIncomingAnnouncedState (because of line `ChangesOnChangedItems Warehouse.ReceiptItem`)
2. Inserting DocumentItem_Materialized (because of line `Is Warehouse.DocumentItem`)

The order of those is undefined, but DocumentItem_Materialized should be inserted first,
because this record is required in database when inserting WarehouseIncomingAnnouncedState.
It is required because WarehouseIncomingAnnouncedState has a reference to DocumentItem,
which in database is implemented as a foreign key to DocumentItem_Materialized.

So, the solution is to break those dependencies into simpler ones: We can specify ChangesOnChangedItems in ComputeWarehouseIncomingAnnouncedState to depend on DocumentItem_Materialized instead of ReceiptItem: **You just need to replace `ChangesOnChangedItems Warehouse.ReceiptItem` with `ChangesOnChangedItems Warehouse.DocumentItem_Materialized` to achieve this.**

Now, instead of:
    
    insert ReceiptItem => insert WarehouseIncomingAnnouncedState
                       => insert DocumentItem_Materialized

we are chaining the computations:

    insert ReceiptItem => insert DocumentItem_Materialized => insert WarehouseIncomingAnnouncedState

**Comment by bantolov** [comment]
Unrelated to this problem, the filters in the example above could be simplified by using a generic filter (FilterCriteria) instead of a custom one (IncomingAnnouncedChangeData).

1. Instead of the existing `ChangesOnChangedItems Warehouse.DocumentItem_Materialized` with IncomingAnnouncedChangeData, write the following:
    ```c
    ChangesOnChangedItems Warehouse.DocumentItem_Materialized
        'FilterCriteria'
        'changedItems => new FilterCriteria("DocumentItemID", "in", changedItems.Select(changedItem => changedItem.ID))';
    ```
2. Now you can remove the 2 occurences of `FilterBy 'Warehouse.IncomingAnnouncedChangeData[]` and remove `Parameter IncomingAnnouncedChangeData`.

**Comment by vinkoSego** [comment]
Thank you!
Your solution works like a clockwork!

Regards
