### ISSUE TITLE
Releases should include built binaries

### ISSUE THREAD

**Issue by Hugibeer** [Rhetos/Rhetos#46]
Releases of versions should include prebuilt Rhetos server dlls. 
I want to take Rhetos and run it immediately, I don't want to bother with setting up development environment and building binaries from source. It can stay as part of the release, but I feel as it would make a life a lot easier for anyone just trying out the technology to have prebuilt binaries.

**Comment by bantolov** [comment]
The binaries for the Rhetos server are now available at <https://github.com/Rhetos/Rhetos/releases> for versions since v2.0.0, and will be available for future releases.

Please not that if you need to reference the Rhetos dlls from your project, it is recommended to use the existing [Rhetos NuGet](https://www.nuget.org/packages?q=rhetos) packages instead.
