### ISSUE TITLE
Extending common entity

### ISSUE THREAD

**Issue by marijok** [Rhetos/Rhetos#55]
Hello,

We would like to add a column to Common.PrincipalHasRole and make it part of existing unique constraint: 

```SQL
CREATE UNIQUE CLUSTERED INDEX [IX_PrincipalHasRole_Principal_Role] ON [Common].[PrincipalHasRole]
(
	[PrincipalID] ASC,
	[RoleID] ASC
)
```

In the dsl we have:

```
Module Common
{
    Entity SecurityUnit
    {
        ShortString Name { Unique; }    
    }

    // Extending existing table so when we add role to user, we need to add a security unit as welll
    Entity PrincipalHasRole
    {
        Reference SecurityUnit Common.SecurityUnit;
    }
}
```

How can we set "Reference SecurityUnit Common.SecurityUnit" to be part of existing unique constraint?

**Comment by SilverHR** [comment]
I'm not aware that Rhetos currently supports deactivating concepts. 

So if you insist adding PrincipalHasRole.SecurityUnit then you can:

Remove "UniqueMultiple 'Principal Role'" from Security.rhe and add new UniqueMultiple in your extension.

OR

You can alter the SQL Index that is the result of the original Unique concept using SqlObject:

SqlObject IX_PrincipalHasRole_Principal_Role_SecurityUnit
"DROP INDEX [IX_PrincipalHasRole_Principal_Role] ON [Common].[PrincipalHasRole]
CREATE UNIQUE CLUSTERED INDEX [IX_PrincipalHasRole_Principal_Role] ON [Common].[PrincipalHasRole](PrincipalID, RoleID, **SecurityUnit**)"
"DROP INDEX [IX_PrincipalHasRole_Principal_Role] ON [Common].[PrincipalHasRole]
CREATE UNIQUE CLUSTERED INDEX [IX_PrincipalHasRole_Principal_Role] ON [Common].[PrincipalHasRole](PrincipalID, RoleID)"
	{
		SqlDependsOn Common.PrincipalHasRole.Principal;
		SqlDependsOn Common.PrincipalHasRole.Role;
		SqlDependsOn Common.PrincipalHasRole.SecurityUnit;
	}

**Comment by bantolov** [comment]
Deactivating the existing features in Rhetos is always more complicated then extending them.

@SilverHR's solution above is a general workaround that can always be used for this kind of situations with database objects.

There is another way to modify this specific index (without dropping and creating it a second time), but the solution is more complex. In the implementation of UniqueMultiple you can find that the existing concept "SqlIndexMultipleFollowingPropertyInfo" can be used to add another property in this index (you will have to specify that the new property is added *after* the "Role" property). This concept currently has no DSL keyword defined, so you will need to extend Rhetos with another helper concept to add this one.

Here is an example of the helper macro concept "AddIndexPropertyAfter", that you can include in you project to add a property to the index:

```C#
[Export(typeof(IConceptInfo))]
[ConceptKeyword("AddIndexPropertyAfter")]
public class AddIndexPropertyAfterInfo : IConceptInfo
{
    [ConceptKey]
    public SqlIndexMultipleInfo SqlIndex { get; set; }

    /// <summary>
    /// The existing indexed property that is last one in the index.
    /// The new property will be added to the index at the position after this one.
    /// </summary>
    [ConceptKey]
    public string PreviousPropertyName { get; set; }

    public string PropertyName { get; set; }
}

[Export(typeof(IConceptMacro))]
public class AddIndexPropertyAfterMacro : IConceptMacro<AddIndexPropertyAfterInfo>
{
    public IEnumerable<IConceptInfo> CreateNewConcepts(AddIndexPropertyAfterInfo conceptInfo, IDslModel existingConcepts)
    {
        return new IConceptInfo[]
        {
            new SqlIndexMultipleFollowingPropertyInfo
            {
                SqlIndex = conceptInfo.SqlIndex,
                PreviousIndexProperty = new SqlIndexMultiplePropertyInfo
                {
                    SqlIndex = conceptInfo.SqlIndex,
                    Property = new PropertyInfo { DataStructure = conceptInfo.SqlIndex.DataStructure, Name = conceptInfo.PreviousPropertyName }
                },
                Property = new PropertyInfo { DataStructure = conceptInfo.SqlIndex.DataStructure, Name = conceptInfo.PropertyName }
            }
        };
    }
}
```

Example of usage in DSL script:

```
Entity PrincipalHasRole
{
    Reference SecurityUnit Common.SecurityUnit;
    ShortString AnotherProperty;

    AddIndexPropertyAfter 'Principal Role'.Role SecurityUnit;
    AddIndexPropertyAfter 'Principal Role'.SecurityUnit AnotherProperty;
}
```

First AddIndexPropertyAfter will add the SecurityUnit property to the existing index (named 'Principal Role') after the Role property. The second one will add AnotherProperty after the SecurityUnit property.
You need to explicitly define where to add the new property because of the declarative nature of Rhetos DSL, the order of lines in the DSL script cannot affect the features, but the order of properties in the index is important.
