### ISSUE TITLE
Overriding claims from role group

### ISSUE THREAD

**Issue by Puzjak** [Rhetos/Rhetos#58]
So i have MainRole which inherits MyClaim from RoleGroup and few different mail roles also inherit that RoleGroup. 
I need to remove MyClaim from MainRole but editing RoleGroup is not an option because other main roles have to stay the same. 

If i insert a row in RolePermission with RoleID = MainRoleID, ClaimID = MyClaimID, IsAuthorized = 0, will that override the permission which MainRole inherits from RoleGroup?

**Comment by bantolov** [comment]
Yes, setting `IsAuthorized = 0` will deny this claim to the user. Deny will always override the allowed permissions from other roles, so if the user has a certain permission allowed by one of his roles and denied by some other role, at the and the permission will be denied.

Please note that denying permissions should be used as a rare exception because it complicates the administration of the permissions in the future.
