### ISSUE TITLE
Performance issue when sending new requests while the previous not finish yet

### ISSUE THREAD

**Issue by ndtung449** [Rhetos/Rhetos#63]
Hi everyone,
I am facing an issue that if I send requests slowly one by one, every request will finish in a timely manner, let say 100ms. But if I send those request faster (80ms/request) then every request will take much more time to finish or even timeout.
I think the issue is because Rhetos accesses database synchronously, not asynchronous.
Has anyone also had this issue before?

**Comment by sstublic** [comment]
There is nothing inherent in the Rhetos design to force synchronous processing of requests. As a web application (depending on the hosting technology used) each request is processed as a separate work unit and is usually assigned to a new thread. These threads will simultaneously query a database according to database settings.

Some web stacks could be configured to queue request and process them synchronously - if I remember correctly enabling sessions in ASP.NET can trigger this behavior on IIS.

So your problem might be due to configurations of web hosting stack/database or some other completely unrelated issue (possibly a Rhetos bug).

We will check out the example you provided and let you know if we can reproduce the behavior.

**Comment by sstublic** [comment]
I took a more detailed look at your example project and found several issues (so far all unrelated to Rhetos).

The basic scenario you describe is when request time is 70ms and you're placing requests at 200ms interval. There nothing suspicious about this, because it ends up like sequential requests with 130ms pause between them.

Things get a lot more complex once you issue requests in intervals of 50ms while each requests requires at least 70ms to complete. This makes requests **execute in parallel and build up** if parallel processing is not fast enough to execute them before new ones are queued.

### This scenario manifests several problems:

1. First and most evident is that timings of requests appear to be completely sequential. When they execute their speed remains constant, but their total execution time gradually increases. You can check this in Chrome developer tools under Network/Timing. There you can see that most request are 'Stalled' most of the time. The main reason for this is that **Chrome has a built in feature which forces them to execute sequentially**. This behaviour is caused by issuing request against the **same URI** (some info here: https://stackoverflow.com/questions/27513994/chrome-stalls-when-making-multiple-requests-to-same-resource). You can circumvent this behavior by appending a changing query parameter to mutate the URI on each request. For example:
```
var myInterval = setInterval(
		() => {
			var rndParam = Math.random().toString();
			fetch('http://localhost:7002/rest/test/TodoItem/?Filters=[{%22Property%22:%22Content%22,%22Operation%22:%22Greater%22,%22Value%22:%22YI%22}]&q=' + rndParam)
				.then(res => res.json())
				.then(console.log)
		}, 10);
setTimeout(() => clearInterval(myInterval), 4000);
```
This change will fix **most** of your problems. Some, however, still remain.

2. Browsers have a **built-in limit of maximum concurrent ajax connections** they will allow (both total and per domain), irrespectively of (1). Some dated info here: https://webmasters.stackexchange.com/questions/90301/how-can-i-tell-chrome-to-use-all-6-concurrent-connections-asap. This means that if your parallel javascript ajax request go beyond this limit, extra requests will again get stalled and get executed at a later time - therefore seem slower.

3. Once we deal with above issues, there is also a performance degradation of the database. After a reasonable amount of parallel requests to the database has been reached, queries will degrade in performance simply due to the nature of available cores/parallel processing power of the server machine.

I suggest you eliminate the above problems from your tests and if you're still encountering issues, let us know. I haven't really eliminated any potential Rhetos problems, but we need a scenario with fewer external factors. Simple C# program which executed REST request in 100 threads simultaneously behaved as expected - with some degradation due to database congestion, but generally fast.

**Comment by ndtung449** [comment]
@sstublic, thank you very much for your time and the useful information you provided. I will think about other factors.
